# Generated by Django 5.1.6 on 2025-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('place_id', models.CharField(default='fakeId', max_length=27)),
                ('full_address', models.CharField(max_length=300)),
                ('coordinates', models.JSONField(default=dict)),
                ('summary', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['place_id'], name='place_id_idx')],
            },
        ),
    ]
