# Generated by Django 5.1.6 on 2025-03-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='mainstream',
            field=models.BooleanField(default=False),
        ),
    ]
