# Generated by Django 5.1.6 on 2025-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_place_mainstream'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='place',
            name='place_id_idx',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(db_index=True, default='fakeId', max_length=27),
        ),
    ]
